### ISSUE TITLE
New way to submit subtask

### ISSUE THREAD

**Issue by idocx** [CederGroupHub/alab_management#11]
## Details
Currently, `alab_management` provides a `BaseTask` class to help to write various tasks like heating, and dispensing easily. In the task definition (subclass of `BaseTask`), it is reasonable for a task to call other tasks (e.g. calling `Moving` task in the `Heating` task to move the crucible into the furnace). 

In the currently setting, the code looks like [this example](https://github.com/CederGroupHub/alab_management/blob/master/examples/simple_example/tasks/heating.py).

However, this is not very elegant as it needs to write many internal parameters like task_id and lab_view

```python
move_to_furnace = Moving(
        sample=self.sample,
        task_id=self.task_id,
        dest=sample_positions[Furnace]["$/inside"][0],
        lab_view=self.lab_view
)
move_to_furnace.run()
```

We are wondering if we can find a more elegant way to submit a task (e.g. define a function to create and run a subtask in the `BaseTask` class).

**Comment by rekumar** [comment]
I suggest making a unique `task_id` for each `BaseTask` instance. Currently, multiple tasks will have the same id (ie `Heating` and the two internally generated `Moving` tasks will have the same id), which I think will cause headaches downstream. If we opt for unique `task_id`s, we can have `BaseTask` generate a unique id upon instantiation to simplify definition.

As for `lab_view`, can we handle this automatically using the sample name?

**Comment by idocx** [comment]
Hi, Rishi,

Yeah, I quite agree that we need a unique `task_id` for each BaseTask instance.

In the system, a `task_id` is generated for a task when an experiment request is processed ([source code here](https://github.com/CederGroupHub/alab_management/blob/master/alab_management/experiment_manager.py#L82)), so that we can refer to one task at any time during execution.

When a task starts to run, it may start many subtasks, which will not have any records in the DB. We used this design because we thought the tasks are predefined so we can always know what is going on inside a task. However, it seems that sometimes the task may change (e.g., doing some subtasks repeated until certain conditions are met). We need a UID for each `BaseTask` instance for better logging.

Before, I was thinking about having a unique `subtask_id` for each task, which can be stored in `LabView` instance. We can have a function in the `LabView` object (something like `create_subtask`) to launch subtasks. We may not be able to infer the `subtask_id` from `sample_name` as it is not unique globally. But we may be able to use `uuid` package to generate a unique ID to identify them.

Thanks!
