### ISSUE TITLE
pip install broken by import in setup.py

### ISSUE THREAD

**Issue by rekumar** [CederGroupHub/alab_management#14]
https://github.com/CederGroupHub/alab_management/blob/234e2603dad7d439181ae72a1d0c8106db36e457/setup.py#L5-L6

We can't import `alab_management` to get version number because `__init__.py` for `alab_management` triggers imports of some packages that are not installed yet. hardcoding version number in `setup.py` for now, we can come up with a more elegant solution later if necessary.

**Comment by idocx** [comment]
Can we put the version info into a file named `VERSION` and we can just read this from the file when we need it?

**Comment by rekumar** [comment]
We can. Could be better to leave versioning up to the CI system, looks like there are some tools (NumPy uses versioneer) to assist in using GitHub version tags (which we can add when merging new version updates to main branch). For now I'll just hardcode into setup.py, we can use a better system once things shape up. 

Will come back to this later
